// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/author/[slug].ts";
import * as $1 from "./routes/api/blog.ts";
import * as $2 from "./routes/api/category/[slug].ts";
import * as $3 from "./routes/article/[slug].tsx";
import * as $4 from "./routes/author/[slug].tsx";
import * as $5 from "./routes/category/[slug].tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/FetchMore.tsx";
import * as $$1 from "./islands/MobileHeader.tsx";
import * as $$2 from "./islands/Search.tsx";

const manifest = {
  routes: {
    "./routes/api/author/[slug].ts": $0,
    "./routes/api/blog.ts": $1,
    "./routes/api/category/[slug].ts": $2,
    "./routes/article/[slug].tsx": $3,
    "./routes/author/[slug].tsx": $4,
    "./routes/category/[slug].tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/FetchMore.tsx": $$0,
    "./islands/MobileHeader.tsx": $$1,
    "./islands/Search.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
